### ISSUE TITLE
bcryptjs no longer using the same method as used in the course.

### ISSUE THREAD

**Issue by ngahika01** [mukeshphulwani66/Instagram-clone-MERN-Stack#14]

**Comment by ngahika01** [comment]
insta-clone\node_modules\bcryptjs\dist\bcrypt.js:214
                nextTick(callback.bind(this, Error("Illegal arguments: "+(typeof
 s)+', '+(typeof salt))));
                                             ^

Error: Illegal arguments: number, number
    at _async (D:\Node\insta-clone\node_modules\bcryptjs\dist\bcrypt.js:214:46)
    at D:\Node\insta-clone\node_modules\bcryptjs\dist\bcrypt.js:223:17
    at new Promise (<anonymous>)
    at Object.bcrypt.hash (D:\Node\insta-clone\node_modules\bcryptjs\dist\bcrypt
.js:222:20)

**Comment by ngahika01** [comment]
nextTick(callback.bind(this, Error("Illegal arguments: "+(typeof
 s)+', '+(typeof salt))));
                                             ^

Error: Illegal arguments: number, number

**Comment by ChitrangSharma** [comment]
it worked fine for me though
